name: Bitcoin Analysis Cron Job
on:
  schedule:
    - cron: '0 */5 * * *'  # Runs every 5 hours
  workflow_dispatch:  # Allows manual triggering
jobs:
  run-bitcoin-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you're using
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas telebot ta persiantools requests
    - name: Run Bitcoin analysis script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: python main.py  # Replace with your script's filename
